# change localhost with respective containers

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: discoveryService
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#          filters:
#            - AuthenticationFilter

#        - id: authenticationService
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/auth/**

        - id: admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/**

        - id: bus-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/buses/**

        - id: route-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/routes/**

        - id: passenger-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/passengers/**

        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/auth/**



